import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Backend from '../components/profile/Backend'
import LanguageCards from '../components/profile/LanguageCards'
import Portfolio from '../components/profile/Portfolio'


export default function Home() {

  return (
    <div>
      <Head>
        <title>Emilien Vaschalde - Developpeur WEB</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header cate="home" />


      <div className='head'>
          <h1>Développeur WEB</h1>
          <h2>Emilien VASCHALDE</h2>
          <div className='bottom'>
            <img src="./assets/img/head2.svg" alt="svg décoration" />
            <img src="./assets/img/head1.svg" alt="svg décoration" />
          </div>
      </div>

      <div className='section1'>
        <div className='photo_profile'>
          <img src="./assets/img/emilien5.png" alt="Emilien Vaschalde, développeur web" />
        </div>
        <p>
          Je suis développeur <span>front end</span> avec des notions de back end. <br />
          Spécialisé <span>ReactJs</span>
        </p>
      </div>


      <div className='language'>
        <img src="./assets/img/front.png" alt="Emilien vaschalde, developpeur front end" />
        <div className='ball ball-1'></div>
        <div className='ball ball-2'></div>
        <div className='ball ball-3'></div>
      </div>
     
      <LanguageCards />

      <Backend />

      <Portfolio />

     <Footer />
    </div>
  )
}
