import Head from 'next/head'
import Header from '../components/Header'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header cate="home" />

      <h1>Emilien Vaschalde</h1>
     
    </div>
  )
}
